export enum LedgerEventType {
  INITIAL_GRANT = 'INITIAL_GRANT',
  TIME_OFF_DEDUCTION = 'TIME_OFF_DEDUCTION',
  CANCELLATION_REFUND = 'CANCELLATION_REFUND',
  ANNIVERSARY_BONUS = 'ANNIVERSARY_BONUS',
  RECONCILIATION_CORRECTION = 'RECONCILIATION_CORRECTION',
  MANUAL_ADJUSTMENT = 'MANUAL_ADJUSTMENT',
}
