export enum LifecycleEvent {
  APPROVE = 'APPROVE',
  REJECT = 'REJECT',
  CANCEL = 'CANCEL',
  HCM_CONFIRMED = 'HCM_CONFIRMED',
  HCM_BUSINESS_REJECTED = 'HCM_BUSINESS_REJECTED',
  HCM_TRANSIENT_FAILURE = 'HCM_TRANSIENT_FAILURE',
  HCM_RETRY = 'HCM_RETRY',
  MAX_RETRIES_EXCEEDED = 'MAX_RETRIES_EXCEEDED',
  COMPLETE = 'COMPLETE',
}
